### ISSUE TITLE
Create useAnalytics hook

### ISSUE THREAD

**Issue by dustinsgoodman** [thisdot/hydrogen-nextjs#12]
A big part of Shopify and eCommerce is collecting analytics. Hydrogen has a `useAnalytics` hook that we should migrate to work in our Next.js setup.

Upstream: https://github.com/Shopify/hydrogen/blob/2023-04/templates/demo-store/app/hooks/useAnalytics.tsx

**Comment by markshenouda** [comment]
The project has been moved to the main starter.dev repo
