### ISSUE TITLE
Build order detail page

### ISSUE THREAD

**Issue by kenslachtajr** [thisdot/hydrogen-nextjs#121]
Assuming this is UI only, then this ticket is a medium or large. We need to debug the code to be able to access this page before we can be certain. Sizing is preliminary and subject to change.

Note from Dustin: I was unable to render the page successfully but there is a page. I need help rendering it before we can set acceptance.

## Acceptance

- [x] Show the order detail info in the page
- [x] Show the order shipping address
- [x] Add a link to go back to account page

**Comment by Megio** [comment]
This is the Order Detail Page:

![Image](https://github.com/thisdot/hydrogen-nextjs/assets/32470461/652a1e9c-47ec-48ba-9c61-0b2a9116a49e)


@kenslachtajr since there are no complex logics in this page, I think this ticket could be sized as a Medium ticket

**Comment by kenslachtajr** [comment]
Great! Good work on getting the issue resolved and getting the preview. I've updated the ticket size.
