### ISSUE TITLE
Debug why build order detail page is not displaying

### ISSUE THREAD

**Issue by kenslachtajr** [thisdot/hydrogen-nextjs#122]
## Description

Currently, we are unable to access the order detail page. There is likely some logic in the code that is not working correctly and needs to be researched. 

Note: timebox this activity to 2 hours and surface to PM if we are unable to find the issue in that time.

**Comment by Megio** [comment]
I was able to fix the bug and reach the order detail page.

In the hydrogen remix demo project just change:

`subtotalPriceV2` --> `subtotalPrice`
`totalTaxV2` --> `totalTax`
