### ISSUE TITLE
Reset/Recover Password Issue

### ISSUE THREAD

**Issue by kenslachtajr** [thisdot/hydrogen-nextjs#123]
## Description

Resetting the password for the first time works, but the next time it won't work because we don’t get an email to reset the password.

Sizing is not a high confidence here as some additional research is required.

**Comment by Megio** [comment]
I found also this old conversation and it seems quite common and still an open issue https://github.com/thisdot/hydrogen-nextjs/pull/136#issue-1815684887

Let's see if we will also have the same "problem" in the deployed version of the project.
