### ISSUE TITLE
error handling on forms inputs

### ISSUE THREAD

**Issue by kenslachtajr** [thisdot/hydrogen-nextjs#125]
## Description

This is something that is not included in the current kit, but it is nice to have. There should be error handling in any form and currently, there is none. There are a lot of forms in the application, so this ticket involves quite a bit of work.

**Comment by Megio** [comment]
- we have added a very simple error-handling logic in our form, the focus of this ticket should be the fact that since we are using server-side forms we are not currently able to clear form errors when we close and re-open the form modal

**Comment by Megio** [comment]
regarding the warning on server I found this open issue, probably the new version of next redirect  breaks something on undici 
https://github.com/nodejs/undici/issues/2046
